export var ExecutionLabData = {
    "EnvironmentList":[],
    "SelectedEnvironment":'',
    "ComponentList":[],
    "SelectedComponent":'',
    "ThreadCountList":[1,2,3,4,5],
    "ReportingInDashboard":"No",
    "ListOfTestScripts":[],
    "SelectedTestScripts":[],
    "TotalPassFailInLastXResults":[],
    "BarChartDataForComponent":[],
    "ScreenShotList":['Each Step','Failure Step'],
    "SelectedScreenShot":'Each Step',
    "RunAtOptionList":['Server','BrowserStack','LamdaTest','SauceLabs'],
    "SelectedRunAtOption":'Server',
    "ScreenOptionList":['Android','iOS'],
    "SelectedScreenOption":'',
    "SelectedThreadCount":1,
    "DeviceList":[],
    "SelectedDevice":'',
    "AllConfigData":{},
    IsErrorOnComponent:false,
    "ExecutionTimeGraphXaxis":[],
    "ExecutionTimeGraphYaxis":[[]],
    "ExecutionTimeColor":['#F39C12'],
    "AssertionResultsForAllResults":{},
    "ExecutionTimeForTestScripts":{},
    IsGlobalError:false,
    GlobalErrorMessage:'',
    IsScreenshotModalOpen:false,
    ImageData:'',
    StepsDetailsForScreenshot:'',

};