export var DashboardData = {
    ListOfTestCycle:[],
    SelectedTestCycle:'',
    TotalTestCase:0,
    TotalDefects:0,
    TotalTestPlan:0,
    TotalTestCaseOnLastExecution:0,
    PassPercentageInLastExecution:0,
    AutomatedandNotAutomatedData:[],
    ColorCodeForAutomatedGraph:[],
    TestPriorityDataXaxis:[],
    TestPriorityDataYaxis:[],
    ColorCodeForTestPriority:[],
    ComponentTestCaseCountXaxisData:[],
    ComponentTestCaseCountYaxisData:[],
    ColorCodeForComponentTestCaseCount:[],
};