export var ConfigData = {
    AllConfigData: {},
    EnvironmentList: [],
    DefaultSelectedEnvironment: '',
    MaxReportCounter: 12,
    DefaultReportTrailCount: 1,
    DefaultSaveDaysToReport: 12,
    DefaultSaveDaysToDevelopment: 1,
    ScreenshotOptionList: ['For failure & success', 'For each step'],
    SelectedScreenshot: 'For failure & success',
    ExecutionPlatformList: ["Android", "iOS"],
    DefaultExecutionPlatform: 'Android',
    EnvUrlList: [],
    SelectedRowFromUrlTable: -1,
    SelectedRowFromEmulatorTable: -1,
    AllEmulatorTableData: [],
    IsDataValidInEmulatorTable: true,
    AllTestManagementToolData: [],
    SelectedRowFromToolTable: -1,
    IsDataValidInToolTable: true,
    AllExecutionServer: ['BrowserStack', 'LamdaTest', 'SauceLabs', 'headspin'],
    IsErrorOnExecutionAt: false,
    ExecutionServer: 'BrowserStack',
    IsErrorOnServerUrl: false,
    ServerUrl: '',
    AllCapabilities: [{
        "platformName": "Android",
        "platformVersion": "",
        "deviceName": "",
        "automationName": "UiAutomator2"
    }],
    CleanUpEnvironment: '',
    SelectedDaysForDelete: '7 Days',
    IsErrorOnCleanUpEnvironment: false,
    IsErrorOnDayToDelete: false,
    SelectedComponent:'',
    ComponentList:[],
    NewComponentName:'',
    IsErrorOnNewComponentName:false,
    ComponentDeleteMessage:'Are you sure,you want to delete the component? After deleting the component, all test cases will be deleted, and you cannot roll back. The application can behave abnormally if test cases are updated or executed by an existing user.',
    ComponentRenameMessage:'Are you sure,you want to rename the component? After updating the component name, all test cases component will be updated.The application can behave abnormally if test cases are updated or executed by an existing user.',
    SelectedSourceComponentToMove:'',
    SelectedDestinationComponentToMove:'',
    ListOfTestIdToMove:[],
    ListOfAllTestID:[],
    AllElementLocator:[],
    IsDataValidInLocatorTable:true,
    SelectedRowFromLocatorTable:-2,
};